service: image-upload

provider:
  name: aws
  runtime: nodejs12.x
  profile: admin
  region: us-east-1
  stage: dev
  environment:
    imageUploadBucket: ${self:custom.imageUploadBucket}
    region: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

plugins:
  - serverless-webpack

package:
  individually: true
  exclude:
    - "**/*"
  include:
    - lib/**

custom:
  imageUploadBucket: sql-bucket-test-2

functions:
  imageUpload:
    handler: lambdas/endpoints/imageUpload.handler
    events:
      - http:
          path: image-upload
          method: POST
          cors: true
# resources:
#   Resources:
#     ImageUploadBucket:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: ${self:custom.imageUploadBucket}
#         AccessControl: PublicRead
